### ISSUE TITLE
What Jess Be Doing

### ISSUE THREAD

**Issue by eliztaylor99** [lcdi/snipe-it#10]
### 2/5/2021

**Accomplished this shift:**
- Completed onboarding materials in Canvas
- Read through wiki on this repo
- Started installation process
- Replaced XAMP with WAMP on my system

**Questions:**

**What Is Needed:**
- The installation is a bit confusing, so I might need somebody to walk through it with me/check what I have done during the next shift
- My WAMP is not working? I tried checking my php version and its not recognizing it as a command

**Working on Next Shift:**
- Meeting on Monday to figure out what to do next

**Comment by eliztaylor99** [comment]
### 2/5/2021

**Accomplished this shift:**
- Had sprint team meeting with Wes and Nate
- Talked about potential project ideas after the inventory system is up
- Reached out to Joe to figure out what teams have what members in order to create groups with permissions in the inventory system
- Started preliminary research on Spotify API

**Questions:**

**What Is Needed:**
- I need a list from Joe of who is on what team with what supervisor, he said he shared it to me in the GZ drive but I don't know what that is and he hasn't replied to my message yet

**Working on Next Shift:**
- Reach out to supervisors to ask them about what teams need what permissions
- Start filling out google sheet with info
- Create test groups and users in the inventory system to see if it works
(creating this comment early so I don't forget and also because I will be working on preliminary research/filling out the groups spreadsheet during the rest of my shift)

**Comment by eliztaylor99** [comment]
### 2/15/2021

**Accomplished this shift:**
- Completed list of students with their project title and supervisor by reaching out to all supervisors
- Familiarized myself with the other 3 programming repos in case we are asked to work on them after our project

**Questions:**

**What Is Needed:**
- Waiting on inventory of lab to be done so that I can ask supervisors what specifically from the lab their team may need access to

**Working on Next Shift:**
- Waiting on full inventory list
- Look more into issues on other projects
- Clone spotify repo and mess around with code & using API

**Comment by eliztaylor99** [comment]
### 2/15/2021

**Accomplished this shift:**
- Continued to familiarized myself with the other 3 programming repos in case we are asked to work on them after our project
- Cloned spotify repo and started looking into how program works
- Started going through React/Typescript tutorials on seating chart wiki page

**Questions:**

**What Is Needed:**
- Waiting on inventory of lab to be done so that I can ask supervisors what specifically from the lab their team may need access to

**Working on Next Shift:**
- Waiting on full inventory list
- Have covid test back, so will go into lab to help Nathan and Wes

**Comment by eliztaylor99** [comment]
### 2/22/2021

**Accomplished this shift:**
- Worked on labeling items and putting in inventory system in the lab with Nathan and Wes

**Questions:**

**What Is Needed:**
- Need access to roof access
- Waiting on full inventory list

**Working on Next Shift:**
- Continue working on inventorying lab if Wes and Nathan don't finish on Tuesday
- Start reaching back out to supervisors

**Comment by eliztaylor99** [comment]
### 3/1/21

**Accomplished this shift:**
- Started reaching out to supervisors asking about permissions
- Talked with team about how we will approach permissions moving forward
- Continued working on React and TypeScript tutorials

**Questions:**


**What Is Needed:**
- Not needed, but I wasn't able to connect to the VPN during my shift because of the wifi being spotty

**Working on Next Shift:**
- Picking up where Wes and Nate leave off in the lab

**Comment by eliztaylor99** [comment]
### 3/5/21

**Accomplished this shift:**
- Worked on tutorials some more
- Talked to Lenora about next steps
- Starting looking more into issues on Seating Chart and getting familiar with code

**Questions:**

**What Is Needed:**

**Working on Next Shift:**
- Working in the lab with Wes and Nathan on last of inventory
- Attend the Seating Chart sprint meeting
- Clone the Seating Chart repo and work through the set up

**Comment by eliztaylor99** [comment]
### 3/8/21

**Accomplished this shift:**
- Cloned Seating Chart repo
- Went through most of set up in readme
- Starting reading through code in order to get better grasp of it

**Questions:**

**What Is Needed:**

**Working on Next Shift:**
- Attend Seating Chart sprint meeting

**Comment by eliztaylor99** [comment]
### 3/22/21

**Accomplished this shift:**
- Worked on user permissions
- Created groups for Team Members, HDT1 & 2, and Sysadmins
- Finished permissions for HDT1 & 2 and Sysadmins, sent test account credentials to bronson and dylan to approve

**Questions:**

**What Is Needed:**
- need to figure out how to let team members check in their assets without being able to check in everybody's asset

**Working on Next Shift:**
- Attend Seating Chart sprint meeting
- hopefully applying HDT1 & 2 and Sysadmin permissions to all users who need it
- fix issue with Team Member permissions

**Comment by eliztaylor99** [comment]
### 3/26/21

**Accomplished this shift:**
- Connected with Dylan to see if he reviewed test accounts
- Looked into self check in issue

**Questions:**

**What Is Needed:**
- need Dylan and Bronson to finish reviewing test accounts
- need to figure out a way to implement self check in on our own, or change check in process

**Working on Next Shift:**
- hopefully applying HDT1 & 2 and Sysadmin permissions to all users who need it
- talk to Nathan and Wes about self check in issue

**Comment by eliztaylor99** [comment]
### 4/5/21

**Accomplished this shift:**
- Connected with Dylan and Bronson to see if they reviewed permissions
- Added permission groups to all team members and sys admins (need to do help desk after dylan/judah reviews test accounts)

**Questions:**

**What Is Needed:**
- need Dylan/Judah to finish reviewing test accounts

**Working on Next Shift:**
- hopefully applying HDT1 & 2 permissions

**Comment by lenora4321** [comment]
Thanks for all your great work this semester!  I wish you luck after graduation!
