### ISSUE TITLE
Occassional "D'oh documentRoot" and 404 errors

### ISSUE THREAD

**Issue by wesbeard** [lcdi/snipe-it#11]
The hosted installation seems to be working as we've been able to log in and enter items, but occassionally it decides to throw a 404 error while we're working on it as well as one that says "documentRoot should be set to public" which it looks like it is. The errors are not at all consistent and will happen in any browser, but at the same time one browser will work while another won't. I could have firefox and chrome both on the login page where one accesses it just fine but the other gets "D'oh". 

![image](https://user-images.githubusercontent.com/59850643/108918427-5a7a3200-75ff-11eb-8622-fe4a2e37dcd3.png)

**Comment by lenora4321** [comment]
URL vs rote IP address: 
![image](https://user-images.githubusercontent.com/54592240/109714282-3626d400-7b70-11eb-8a18-4e53d8901709.png)
This may be an issue with the /etc/httpd/conf.d/snipeit....... file

**Comment by lenora4321** [comment]
Following up to the issue before, I changed the site config files to match "inventory.lcdi" instead of "snipeit.example.com", which made me think to look at the IP address.  Why is "inventory.lcdi" associated with 2 IP addresses, ```.35``` and ```.36```?  If you go to "inventory.lcdi", I think it might be taking you to ```192.168.2.35``` instead of where the site is actually at ```.36```.  I have yet to encounter an issue with the "D'oh" connecting directly to the IP address, only with the URL.
![image](https://user-images.githubusercontent.com/54592240/109839114-cb7ba400-7c14-11eb-9449-dccd71d6f5f0.png)

**Comment by lenora4321** [comment]
Also, did I accidently kill the image on the login screen somehow?  Anyone else wanna test on their device?
![image](https://user-images.githubusercontent.com/54592240/109840089-bf441680-7c15-11eb-8c2f-98626f79069d.png)

**Comment by lenora4321** [comment]
Submitted a trouble ticket for this

**Comment by lenora4321** [comment]
Trouble ticket got solved, not inventory.lcdi only points to 192.168.2.36, as it should.  This did not, however, fix the problem, just narrows down the cause.  Next, I'm look at browsers.  Every browser I have is able to access the correct site via the URL *and* IP address, **except** Chrome, which has trouble only on the URL.  See attached screenshot for summary.  I want some others to confirm that this issue persists on machines other than mine.
![image](https://user-images.githubusercontent.com/54592240/110155122-25b26b80-7db3-11eb-933f-51cc51250cfa.png)

**Comment by wesbeard** [comment]
Nice work on this Lenora, Nate and I didn't encounter a "D'oh" at all this shift, trying on multiple browsers, refreshes, etc all on the inventory.lcdi URL. The image thing is an issue and we're looking into it but for the mean time we disabled the images in the branding altogether until we can get it figured out.

**Comment by lenora4321** [comment]
So it turns out the issue is pretty much fixed; I just had to flush my DNS cache and that's why I was still getting errors on my end.  Command on Windows: ```ipconfig /flushdns```
