### ISSUE TITLE
Deliverable

### ISSUE THREAD

**Issue by lenora4321** [lcdi/snipe-it#14]
For the programmer team, most of our deliverable is our code and the work we have put out over the course of the semester; however, a little documentation is in order.  Please make a copy of the linked document template, read the instructions, and write your answers.  Send via **email** or **slack** or share via **google docs** the finished copy with your name on it to Wes and/or `lenora.batcher@gmail.com`  or slack.

**Comment by wesbeard** [comment]
Should be done!

https://docs.google.com/document/d/1yDzZrOHDzyU90JF5guO2O8WrWngwQ48sTXEYMqTRIzc/edit?usp=sharing
