### ISSUE TITLE
LDAP Passwords

### ISSUE THREAD

**Issue by lenora4321** [lcdi/snipe-it#2]
The program has LDAP password compatibility so that would be a good thing to set up once we get it hosted.

**Comment by wesbeard** [comment]
This can be LDAP or Active Directory integration actually, but I'm not sure which one the Leahy Center uses. I know we use Team Password Manager but past that I don't know anything about it. The good thing is that all we need to integrate it is get the connection information for the server like what can be seen below. 

![image](https://user-images.githubusercontent.com/59850643/106672861-c9bfb180-657e-11eb-8aad-e4f16677a052.png)

**Comment by wesbeard** [comment]
Support responded but the conversation is ongoing, still need the final LDAP information before we can actually test the integration.

**Comment by wesbeard** [comment]
LDAP is continuing to be an issue even though it seems like I have all the information we need. We're just getting a strange empty error message that doesn't give us much to work off of.
Error:
![image](https://user-images.githubusercontent.com/59850643/110552269-02662400-8105-11eb-9362-7b42d4de441a.png)
Current LDAP credintials:
![image](https://user-images.githubusercontent.com/59850643/110552365-32adc280-8105-11eb-832e-f74387af7bcf.png)

**Comment by wesbeard** [comment]
Complete!
