### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by lenora4321** [lcdi/snipe-it#3]
Snipe-IT has a built in menu for slack integration using web hooks, we could set it up to send messages to a specified channel to track updates to the system.

**Comment by lenora4321** [comment]
Migrated from Tello, Wes said: "I tried to set it up using my test workspace but I don't think it'll work with my local testing environment without a local SSL certificate, so I think it's something were going to have to use when we actually have it working. The process is super easy so it shouldn't be a problem to come back to it."

**Comment by wesbeard** [comment]
I was able to get it integrated on my bot testing server, so all we need to do to integrate it with the Leahy Center is probably create a channel for it and get the webhook URL for the server.

![image](https://user-images.githubusercontent.com/59850643/106671521-a6940280-657c-11eb-84a8-e1996e954efb.png)
