### ISSUE TITLE
Catalog actual inventory

### ISSUE THREAD

**Issue by lenora4321** [lcdi/snipe-it#5]
Add what we have to the existing inventory system. This may require going in to the lab, attaching labels, scanning and testing.

**Comment by wesbeard** [comment]
As of today we are at 150 assets entered and labeled, although we're currently out of label sheets we're getting more to continue labeling as well as double labeling whatever needs it. We've done everything in 300 and 301 that we can immediately tell needs to be inventoried, and we've started on Roof Access.

**Comment by NathanDiMauro** [comment]
217 items cataloged!
