### ISSUE TITLE
Stucturing

### ISSUE THREAD

**Issue by lenora4321** [lcdi/snipe-it#7]
Input what groups we have, who is in what group, if there are any restrictions to being able to check things out, admin privileges, etc.  Make sure to document this, maybe even with a visual.  This may involve the LDAP integration, depending upon how we are doing this.  Also, we need to discuss with the client whether we are checking assets out to group or individuals or desks or what.

**Comment by NathanDiMauro** [comment]
Our structuring doc can be found at [this ](https://docs.google.com/spreadsheets/d/1ETCHNPKWQ51BqE_pRJ72-Is79k332Zp_eLzwU03HosU/edit?usp=sharing) link. 
https://docs.google.com/spreadsheets/d/1ETCHNPKWQ51BqE_pRJ72-Is79k332Zp_eLzwU03HosU/edit?usp=sharing

**Comment by wesbeard** [comment]
This should be finished as of what we wanted to do this semester
