### ISSUE TITLE
Nathan DiMauro's Daily Progress

### ISSUE THREAD

**Issue by NathanDiMauro** [lcdi/snipe-it#8]
**Accomplished this shift:**

- Completed the Leahy Center on-boarding process.(Except the VPN stuff)
- Read through the github wiki
- Made my daily progress card
- Cloned the git repo and began the snipe-it intall

**Questions:**

**What Is Needed:**
- I need Bronson to send out password resets to get on the leahy center VPN

**Working on Next Shift:**
- fininsh installing snipe-it and get to work

**Comment by NathanDiMauro** [comment]
Accomplished this shift:
- Learned how inventory system works
- watched the workforce announcement video
- got into the Leahy Center VPN
- began to look into snipe-it issues
- began looking into possible future projects

Questions:
- What is going on with Murat and our group? Should he be meeting with us?

What Is Needed:
- lab access to begin work on the physical side of the snipe-it project

Working on Next Shift:
- Look into future projects

**Comment by NathanDiMauro** [comment]
Accomplished this shift:
- read some more spoify docs
- messed around with the spoify docs web client to better understand how the api works
- Looked at the previous leahy center spotify github repo
- Looked into the ticket-system github repo
- Began the PHP training on the github wiki

Questions:

What Is Needed:
- lab access to begin work on the physical side of the snipe-it project

Working on Next Shift:
- going to the lab to do the physical inventory managment work

**Comment by NathanDiMauro** [comment]
Accomplished this shift:
- started physical labeling at the lab
- labeled 35 devices
- tried to print labels but ran into issues with printing

Questions:

What Is Needed:
- We need to figure out our label printing issues 

Working on Next Shift:

- continue to work on physical labeling

**Comment by NathanDiMauro** [comment]
Accomplished this shift:

- continued physical labeling at the lab
- got another 30 devices
- got labels to print properly

Questions:

What Is Needed:

Working on Next Shift:
- continue to work on physical labeling

**Comment by NathanDiMauro** [comment]
Accomplished this shift:

- continued physical labeling at the lab

Questions:

What Is Needed:

Working on Next Shift:
- finish labeling

**Comment by NathanDiMauro** [comment]
Accomplished this shift:

- continued physical labeling at the lab

Questions:

What Is Needed:

Working on Next Shift:

- Print out last of the labels

**Comment by NathanDiMauro** [comment]
Accomplished this shift:
- Finished physical labeling at the lab
- Printed out all duplicate labels 
- Reworked the categories in snipe-it to be more concise 

Questions:

What Is Needed:

Working on Next Shift:

**Comment by NathanDiMauro** [comment]
Accomplished this shift:

- Went back to the lab to finalize physical work
- looked into logo issue
- Started work on blog post Joe wants

Questions:


What Is Needed:

Working on Next Shift:

**Comment by NathanDiMauro** [comment]
Accomplished this shift:

- Finished my section of blog post Joe wants
- meet with Lenora
- Wrote a tweet
- looked more into the logo issue

Questions:

What Is Needed:

Working on Next Shift:
- Going to the phyical lab one last time to go over the inventory system with Joe

**Comment by NathanDiMauro** [comment]
Accomplished this shift:

- Team decided not to go to the lab
- Finialized blog
- looked into the logo issue 
- Met with Joe and Wes to go over the project
- looked into the status lables and having checked out items appear on the pi graph

Questions:

What Is Needed:
- I need to talk more with @lenora4321 about the logo issue and try to figure out what config file is causing the problem 

Working on Next Shift:
- spring break shift off

**Comment by NathanDiMauro** [comment]
Accomplished this shift:
- watched update video
- worked on the [logo ](https://github.com/lcdi/snipe-it/issues/12)issue #12 


Questions:

What Is Needed:

Working on Next Shift:
- fininsh the logo issue
- check on the permissions work done by Jess yesterday so I know whats going on with that

**Comment by NathanDiMauro** [comment]
Accomplished this shift:
- Looked through the permissions
- still working on the [logo ](https://github.com/lcdi/snipe-it/issues/12)issue #12 


Questions:

What Is Needed:

Working on Next Shift:

**Comment by NathanDiMauro** [comment]
Accomplished this shift:

- Reviewed Logo fix
- added a new logo
- created tweet 
- Looked into self check-in

Questions:

What Is Needed:

Working on Next Shift:

**Comment by NathanDiMauro** [comment]
Accomplished this shift:
- Team decided work on the inventory system is pretty much done except for assigning roles to the individuals. 
- Began to familairize myself with the seating chart git 
- Worked through seating chart tutorials

Questions:

What Is Needed:

Working on Next Shift:
- finish seating chart tutorials
- begin work on seating chart

**Comment by lenora4321** [comment]
Thanks for all your hard work over this semester!
