### ISSUE TITLE
What Has Wes Done

### ISSUE THREAD

**Issue by wesbeard** [lcdi/snipe-it#9]
Things that do be has been done:

**Comment by wesbeard** [comment]
# 2/2/2021

## Accomplished this shift:
- Met with the programming team to figure out the semester
- Organized with inventory team to figure out when we can meet and go in person to categorize and label assets
- Figured out slack integration and tested it on my test slack server, it works well and sends message alerts when assets are checked in or out
- Helped others with setup issues and questions

## TODO:
- Figure out when we can meet in person to categorize everything
- Finish migrating the hosting to the permanent address so it links to the homepage
- Better understand LDAP/AD integration so we can get that working once it's set up on the permanent address

**Comment by wesbeard** [comment]
# 2/8/2021

## Accomplished this shift:
- Sprint meeting with the team to introduce them to Snipe-IT
- Went over how it operates so they can set up their own admin accounts and add test assets
- Organized when we would meet in person to catalog the assets, it's looking like next Monday the 15th
- Talked about project ideas to work on alongside inventory, either a Spotify client for queueing music when working in the lab or some kind of open source contribution.
- Jess is working on identifying which groups at the Leahy Center need which permissions and access to specific groups of assets
- Put in a ticket for LDAP so I'm waiting to get that information along with the ticket for moving the URL to the permanent address.

## TODO
- See if support responds with the LDAP info and if so then get that set up
- Keep researching alternative projects, like looking into what can be done with the Spotfiy API
- Look into some possible open source repositories that we could contribute to

**Comment by wesbeard** [comment]
# 2/9/2021

## Accomplished this shift:
- Met with Lenora and talked about where the inventory project is currently standing
- Talked about what project could be done while remote and waiting to go in person
- Decided that the team could be useful in helping with the ticket system but also that the Spotify project could be a good fallback if there was ever a void of things to be worked on
- Checked in on the tickets but none of them are done yet, unfortunately
- No progress can be made on inventory until the tickets are updated by support or we are able to go in person to catalog so I started working on other projects
- Lenora explained the ticketing system to me so I'd be caught up on the project
- Looked over the issues and familiarized myself with the repo as much as I could at this early stage
- Also cloned the old Spotify repo to see what that looked like, started messing with the React and recalling what I knew about it, as well as typescript which it also uses, class Kevin

## TODO
- Continue waiting for the support tickets, maybe raise the urgency if need be
- Go in person to start cataloging items, Dylan said he and his team could help if needed
- Start improving the Spotify project while waiting for the ticket system project to get off the ground

**Comment by wesbeard** [comment]
# 2/15 & 2/16/2021

## Accomplished these shifts:
- Cleaned up the system, removed test data and unused accounts, etc
- Categorized and entered 80+ items into the inventory system, completed most of 300 and 301 that we could find and thought needed to be inventoried
- Found the right Snipe-IT and printer settings for printing the labels so we were able to print them for the first 60 items
- Physically labeled the first 60 items 
## TODO
- Encountering a problem with accessing the page occasionally, updated the ticket but it's still happening so I'll have to follow up with that next week
- Obtain the final LDAP information we need to set up Active Directory
- Continue adding items to the system from 300/301 and possibly the stuff in Roof Access if we finish those
- Print more labels (the sheets have 30 per page so we need to wait until we have 90, 120, etc to make efficient use of the pages)

**Comment by wesbeard** [comment]
# 2/22/21

## Accomplished this shift:
- Entered most of the remaining items into the system
- Printed all labels for items through 120, but we only have one label sheet left so we're gonna try to make it count
## TODO
- Enter all the remaining items and label them
- Figure out all the things that may need to be double labeled (case and device etc)
- Look at what needs to be labeled in Roof Access
- Dylan said he'd have his team put together some raspberry pi kits so we'd need to label those
- Figure out what assets aren't in the lab and enter those
- Order more labels since we'll probably need them

**Comment by wesbeard** [comment]
# 2/23/21

## Accomplished this shift:
- Added another 62 items to the system and printed label for the first 30
- Responded to ticket regarding LDAP, no progress on that yet
- Still grappling with the "D'oh" bug but we're making progress, Lenora said she'd take a look at the server since I wasn't able to see anything obvious and she set a lot of it up so hopefully we'll resolve it soon
## TODO
- Still need to finished entering items although we're almost done, the only things left are things that we need to ask about or are in the possession of employees
- Need more label paper because we're out and don't have enough to print the labels for the last 30+ items, Joe said he's going to have more available to us for our next shift so we should be able to continue then
- Follow up on the LDAP info so we can get Active Directory working
- Track down the "D'oh" bug once and for all

**Comment by wesbeard** [comment]
# 3/1/21

## Accomplished this shift:
- Met with the team to catch up on what the project is looking like right now and what everyone should be working on.
- We were able to narrow down the categories being used in the system so that each one has at least 5 assets (we definitely did not end up needing a category just for drones).
- Dylan and I looked into inputting the LDAP information that was still needed but for some reason we weren't able to get it working even though it seems like all of it is correct. 
- Googled for other cases of LDAP sync failure and may have some possible solutions to talk over with Dylan.
- Also looked into the "D'oh" bug and didn't make too much progress, the configuration really does look fine and the fact that it works intermittently lends to the idea that it's more complicated than just a configuration error.
## TODO
- Go in person to finish entering assets and printing labels, some things still need labels while others still need to be double labeled.
- Keep at the LDAP issue, there's got to be something wrong with it and I'm sure we can figure it out.
- See if Lenora can see something that I missed in the server config that could be causing our connection bug.

**Comment by wesbeard** [comment]
# 3/2/21

## Accomplished this shift:
- Entered some items from 301 that we hadn't found into the system as well as double labeled a few things like the cameras that really needed it.
- Labeled everything that was remaining in the system from last week as well as everything entered today, now absolutely everything should have a label that needs one.
- Tested the barcode scanning options and the 2D barcodes work really nicely, you just scan them on your phone and they redirect you to the site url so you can check things out on the go.
- We could get a standalone QR code scanner to act in place of the 1D scanner.
- Unfortunately our asset tag format doesn't seem to be compatible with C128 barcodes so the 1D codes aren't going to function. The plan is to use QR instead.
- Looked at the server config to see if I could fix the "D'oh" error but I didn't see anything new, there's still the issue of the multiple installations that could be causing some confusion but all in all it looks ok on the surface.
## TODO
- Continue to look into the "D'oh" error, hopefully Lenora can make a breakthrough
- Work with Dylan next week to get LDAP actually working
- Enter any remaining items that may be outside of the lab into the system.
- Look into getting a QR code scanner if that's something that's desired.

**Comment by wesbeard** [comment]
# 3/8/21

## Accomplished this shift:
- Put a few new items into the system as well as double labeled a bunch of items that we thought needed them
- Looked into the "D'oh" error to see if we could get it to happen again but it didn't happen at all for the entire shift no matter what we tried
- Looked into the issue of the broken branding images but that's going to need to wait for now
- Started working on the blog post that we've been requested to write
## TODO
- Implement LDAP
- Make sure all physical items that should be in the system are in the system
- Fix branding images

**Comment by wesbeard** [comment]
# 3/9/21

## Accomplished this shift:
- Met with Lenora to talk about the current state of the project
- It looks like what she did completely fixed the "D'oh" error as far as we can currently tell
- Worked on the blog post for marketing, I think it's mostly complete but I need to get feedback from DJ
- Looked more into LDAP but no progress as of yet

## TODO
- Finish the blog post up to marketing's specifications
- Figure out LDAP, it's still just giving an empty error box when I try to sync it so I can't tell if it's a problem with Snipe-IT or our the credintials we're trying to test

**Comment by wesbeard** [comment]
# 3/22/21

## Accomplished this shift:
- Had a sprint meeting to organize what were we were doing for today/this week
- Worked with Nate on fixing the branding issue
- Worked with Jess on the permissions system and working it around what Snipe-IT allows and is intended to do
- Finished editing the blog post, as far as I can tell there's nothing else to be done there
- The project is almost finished, in the home stretch
- Also, we ran into a weird bug with requesting assets were it kicks you to an unknown page

## TODO
- Finish slack integration
- Check out the weird requestible bug

**Comment by wesbeard** [comment]
# 3/23/21

## Accomplished this shift:
- Coordinated with Alex to get the SSL certificate set up so that we can use https://
- Looked further into the "500 Server Error" bug that pops up when attempting to open requestables
- Google doesn't seem to be much help, it seems like a pretty obscure error
- Thought it might have something to do with adblock/extensions but it doesn't look like it
- Talked with Dylan to get a better idea of how the system was going to be used from a sys-admin/helpdesk perspective
     - It seems like he's thinking that the people using the system are gonna have generally higher permissions and will mostly be people on teams like helpdesk
     - This might affect how we're doing our permissions/what features need to be included for each permission group
- Talked with Lenora to set up a slack channel in the Leahy Center server for the Inventory slack bot 

## TODO
- Continue looking into the "500 Server Error" bug
- Go over permission and groups again
- Hook up the slack bot to the endpoint created by Lenora

**Comment by wesbeard** [comment]
# 4/5/21

## Accomplished this shift:
- Had a sprint meeting with the team, Nate's pretty much done with what he has to do for this project and Jess is finishing up
- Updated the branding now that it's fixed, the favicon isn't really working but I can't remember if it ever did lol
- Messaged support about the insecure SSL certificate when accessing the site through https, hopefully that'll be fixed soon
- Connected Snipe-IT to the slack endpoint Lenora messaged me
- Messaged Lenora about changing the URL on homepage so that it uses https since before it would redirect you to just inventory.lcdi which would use http by default
- Updated the LDAP filter settings to only sync users with a valid email
- Looked into the *500 Server Error* bug on requestables, didn't really make much progress but this [github issue](https://github.com/snipe/snipe-it/issues/192) might be helpful in the future

## TODO
- Continue looking into the *500 Server Error* bug
- Follow up with Lenora on the slack bot since I can't actually see the #inventory channel yet
- Follow up on the SSL certificate issue

**Comment by wesbeard** [comment]
# 4/6/21

## Accomplished this shift:
- Continued looking into the *500 Server Error* bug, it seems somewhat unique, or at least I haven't been able to find any other threads that have an identical issue
- Might have a solution, we'll see
- I got locked out of the VM for a while so I messaged Bronson to get that access back
- Met with Lenora to check in and talk about where the project is
- Started planning wrap up work like the deliverable
## TODO
- Keep working on fixing *500 Server Error*
- Finish working on the deliverable
- Any other wrap up stuff that needs to be done

**Comment by wesbeard** [comment]
# 4/12/21

## Accomplished this shift:
- Organized with the team to figure out what we needed to do for wrap up
- Worked on my deliverable write up
- Went over old issues to make sure everything was up to date
- Formatted the deliverables so they had a similar style
## TODO
- Finish any other wrap-up tasks that need to be done
- Implement something to try and fix the server error, although I'm hesitant to do anything extreme this late in the semester

**Comment by lenora4321** [comment]
Nice; well documented as always.  Great working with you this semester, Wes, and great job leading your team!
